In [1]:
import os

import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 10)
pd.set_option('display.notebook_repr_html', True)
pd.set_option('display.max_columns', 10)

import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

In [4]:
df = pd.read_csv(os.path.join('..', 'datasets', 'dataset-06-storms.csv.gz'))

In [3]:
df

,STATE__,BGN_DATE,BGN_TIME,TIME_ZONE,COUNTY,...,LONGITUDE,LATITUDE_E,LONGITUDE_,REMARKS,REFNUM
0,1.0,4/18/1950 0:00:00,130,CST,97.0,...,8812.0,3051.0,8806.0,NaN,1.0
1,1.0,4/18/1950 0:00:00,145,CST,3.0,...,8755.0,0.0,0.0,NaN,2.0
2,1.0,2/20/1951 0:00:00,1600,CST,57.0,...,8742.0,0.0,0.0,NaN,3.0
3,1.0,6/8/1951 0:00:00,900,CST,89.0,...,8626.0,0.0,0.0,NaN,4.0
4,1.0,11/15/1951 0:00:00,1500,CST,43.0,...,8642.0,0.0,0.0,NaN,5.0
...,...,...,...,...,...,...,...,...,...,...,...
902292,56.0,11/30/2011 0:00:00,10:30:00 PM,MST,7.0,...,0.0,0.0,0.0,EPISODE NARRATIVE: A strong cold front moved s...,902293.0
902293,30.0,11/10/2011 0:00:00,02:48:00 PM,MST,9.0,...,0.0,0.0,0.0,EPISODE NARRATIVE: A strong westerly flow alof...,902294.0
902294,2.0,11/8/2011 0:00:00,02:58:00 PM,AKS,213.0,...,0.0,0.0,0.0,EPISODE NARRATIVE: A 960 mb low over the south...,902295.0
902295,2.0,11/9/2011 0:00:00,10:21:00 AM,AKS,202.0,...,0.0,0.0,0.0,EPISODE NARRATIVE: A 960 mb low over the south...,902296.0
902296,1.0,11/28/2011 0:00:00,08:00:00 PM,CST,6.0,...,0.0,0.0,0.0,EPISODE NARRATIVE: An intense upper level low ...,902297.0

In [5]:
df.shape

(902297, 37)

In [6]:
df.columns

Index([u'STATE__', u'BGN_DATE', u'BGN_TIME', u'TIME_ZONE', u'COUNTY',
       u'COUNTYNAME', u'STATE', u'EVTYPE', u'BGN_RANGE', u'BGN_AZI',
       u'BGN_LOCATI', u'END_DATE', u'END_TIME', u'COUNTY_END', u'COUNTYENDN',
       u'END_RANGE', u'END_AZI', u'END_LOCATI', u'LENGTH', u'WIDTH', u'F',
       u'MAG', u'FATALITIES', u'INJURIES', u'PROPDMG', u'PROPDMGEXP',
       u'CROPDMG', u'CROPDMGEXP', u'WFO', u'STATEOFFIC', u'ZONENAMES',
       u'LATITUDE', u'LONGITUDE', u'LATITUDE_E', u'LONGITUDE_', u'REMARKS',
       u'REFNUM'],
      dtype='object')

In [7]:
df = df.set_index('REFNUM')

In [8]:
df

,STATE__,BGN_DATE,BGN_TIME,TIME_ZONE,COUNTY,...,LATITUDE,LONGITUDE,LATITUDE_E,LONGITUDE_,REMARKS
REFNUM,,,,,,,,,,,
1.0,1.0,4/18/1950 0:00:00,130,CST,97.0,...,3040.0,8812.0,3051.0,8806.0,NaN
2.0,1.0,4/18/1950 0:00:00,145,CST,3.0,...,3042.0,8755.0,0.0,0.0,NaN
3.0,1.0,2/20/1951 0:00:00,1600,CST,57.0,...,3340.0,8742.0,0.0,0.0,NaN
4.0,1.0,6/8/1951 0:00:00,900,CST,89.0,...,3458.0,8626.0,0.0,0.0,NaN
5.0,1.0,11/15/1951 0:00:00,1500,CST,43.0,...,3412.0,8642.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
902293.0,56.0,11/30/2011 0:00:00,10:30:00 PM,MST,7.0,...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A strong cold front moved s...
902294.0,30.0,11/10/2011 0:00:00,02:48:00 PM,MST,9.0,...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A strong westerly flow alof...
902295.0,2.0,11/8/2011 0:00:00,02:58:00 PM,AKS,213.0,...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A 960 mb low over the south...
902296.0,2.0,11/9/2011 0:00:00,10:21:00 AM,AKS,202.0,...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A 960 mb low over the south...
902297.0,1.0,11/28/2011 0:00:00,08:00:00 PM,CST,6.0,...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: An intense upper level low ...

In [9]:
df.isnull()

,STATE__,BGN_DATE,BGN_TIME,TIME_ZONE,COUNTY,...,LATITUDE,LONGITUDE,LATITUDE_E,LONGITUDE_,REMARKS
REFNUM,,,,,,,,,,,
1.0,False,False,False,False,False,...,False,False,False,False,True
2.0,False,False,False,False,False,...,False,False,False,False,True
3.0,False,False,False,False,False,...,False,False,False,False,True
4.0,False,False,False,False,False,...,False,False,False,False,True
5.0,False,False,False,False,False,...,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
902293.0,False,False,False,False,False,...,False,False,False,False,False
902294.0,False,False,False,False,False,...,False,False,False,False,False
902295.0,False,False,False,False,False,...,False,False,False,False,False
902296.0,False,False,False,False,False,...,False,False,False,False,False
902297.0,False,False,False,False,False,...,False,False,False,False,False

In [10]:
df.isnull().sum()

STATE__            0
BGN_DATE           0
BGN_TIME           0
TIME_ZONE          0
COUNTY             0
               ...
LATITUDE          47
LONGITUDE          0
LATITUDE_E        40
LONGITUDE_         0
REMARKS       287433
dtype: int64

In [13]:
# df.FATALITIES.isnull.sum()

df.FATALITIES.isnull().sum()

0

In [14]:
df.isnull().sum().sum()

6645709

In [15]:
n = df.shape[0]

for column in df.columns:
    count = df[column].isnull().sum()
    if count > 0:
        print '{:10s} {:6d} {:3.0f}%'.format(column, count, 100. * count / n)

COUNTYNAME   1589   0%
BGN_AZI    547332  61%
BGN_LOCATI 287743  32%
END_DATE   243411  27%
END_TIME   238978  26%
COUNTYENDN 902297 100%
END_AZI    724837  80%
END_LOCATI 499225  55%
F          843563  93%
PROPDMGEXP 465934  52%
CROPDMGEXP 618413  69%
WFO        142069  16%
STATEOFFIC 248769  28%
ZONENAMES  594029  66%
LATITUDE       47   0%
LATITUDE_E     40   0%
REMARKS    287433  32%

In [16]:
df.dropna()

Empty DataFrame
Columns: [STATE__, BGN_DATE, BGN_TIME, TIME_ZONE, COUNTY, COUNTYNAME, STATE, EVTYPE, BGN_RANGE, BGN_AZI, BGN_LOCATI, END_DATE, END_TIME, COUNTY_END, COUNTYENDN, END_RANGE, END_AZI, END_LOCATI, LENGTH, WIDTH, F, MAG, FATALITIES, INJURIES, PROPDMG, PROPDMGEXP, CROPDMG, CROPDMGEXP, WFO, STATEOFFIC, ZONENAMES, LATITUDE, LONGITUDE, LATITUDE_E, LONGITUDE_, REMARKS]
Index: []

[0 rows x 36 columns]

In [17]:
df.dropna(axis = 1)

,STATE__,BGN_DATE,BGN_TIME,TIME_ZONE,COUNTY,...,INJURIES,PROPDMG,CROPDMG,LONGITUDE,LONGITUDE_
REFNUM,,,,,,,,,,,
1.0,1.0,4/18/1950 0:00:00,130,CST,97.0,...,15.0,25.0,0.0,8812.0,8806.0
2.0,1.0,4/18/1950 0:00:00,145,CST,3.0,...,0.0,2.5,0.0,8755.0,0.0
3.0,1.0,2/20/1951 0:00:00,1600,CST,57.0,...,2.0,25.0,0.0,8742.0,0.0
4.0,1.0,6/8/1951 0:00:00,900,CST,89.0,...,2.0,2.5,0.0,8626.0,0.0
5.0,1.0,11/15/1951 0:00:00,1500,CST,43.0,...,2.0,2.5,0.0,8642.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
902293.0,56.0,11/30/2011 0:00:00,10:30:00 PM,MST,7.0,...,0.0,0.0,0.0,0.0,0.0
902294.0,30.0,11/10/2011 0:00:00,02:48:00 PM,MST,9.0,...,0.0,0.0,0.0,0.0,0.0
902295.0,2.0,11/8/2011 0:00:00,02:58:00 PM,AKS,213.0,...,0.0,0.0,0.0,0.0,0.0
902296.0,2.0,11/9/2011 0:00:00,10:21:00 AM,AKS,202.0,...,0.0,0.0,0.0,0.0,0.0
902297.0,1.0,11/28/2011 0:00:00,08:00:00 PM,CST,6.0,...,0.0,0.0,0.0,0.0,0.0

In [18]:
df.dropna( how = 'all', axis = 1)

,STATE__,BGN_DATE,BGN_TIME,TIME_ZONE,COUNTY,...,LATITUDE,LONGITUDE,LATITUDE_E,LONGITUDE_,REMARKS
REFNUM,,,,,,,,,,,
1.0,1.0,4/18/1950 0:00:00,130,CST,97.0,...,3040.0,8812.0,3051.0,8806.0,NaN
2.0,1.0,4/18/1950 0:00:00,145,CST,3.0,...,3042.0,8755.0,0.0,0.0,NaN
3.0,1.0,2/20/1951 0:00:00,1600,CST,57.0,...,3340.0,8742.0,0.0,0.0,NaN
4.0,1.0,6/8/1951 0:00:00,900,CST,89.0,...,3458.0,8626.0,0.0,0.0,NaN
5.0,1.0,11/15/1951 0:00:00,1500,CST,43.0,...,3412.0,8642.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
902293.0,56.0,11/30/2011 0:00:00,10:30:00 PM,MST,7.0,...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A strong cold front moved s...
902294.0,30.0,11/10/2011 0:00:00,02:48:00 PM,MST,9.0,...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A strong westerly flow alof...
902295.0,2.0,11/8/2011 0:00:00,02:58:00 PM,AKS,213.0,...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A 960 mb low over the south...
902296.0,2.0,11/9/2011 0:00:00,10:21:00 AM,AKS,202.0,...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A 960 mb low over the south...
902297.0,1.0,11/28/2011 0:00:00,08:00:00 PM,CST,6.0,...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: An intense upper level low ...

In [21]:
df[df.duplicated()]

,STATE__,BGN_DATE,BGN_TIME,TIME_ZONE,COUNTY,...,LATITUDE,LONGITUDE,LATITUDE_E,LONGITUDE_,REMARKS
REFNUM,,,,,,,,,,,
19.0,1.0,5/10/1952 0:00:00,900,CST,57.0,...,3344.0,8745.0,0.0,0.0,NaN
20.0,1.0,5/10/1952 0:00:00,900,CST,57.0,...,3344.0,8745.0,0.0,0.0,NaN
260.0,1.0,7/4/1960 0:00:00,1750,CST,13.0,...,3139.0,8636.0,0.0,0.0,NaN
603.0,1.0,5/14/1967 0:00:00,2330,CST,77.0,...,3453.0,8730.0,0.0,0.0,NaN
604.0,1.0,5/14/1967 0:00:00,2330,CST,77.0,...,3453.0,8730.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
900771.0,38.0,10/7/2011 0:00:00,03:00:00 PM,CST,7.0,...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A strong early October low ...
900806.0,27.0,10/7/2011 0:00:00,04:00:00 PM,CST,1.0,...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A strong early October low ...
900807.0,36.0,10/29/2011 0:00:00,01:00:00 PM,EST,57.0,...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: An early season winter stor...
900808.0,38.0,10/24/2011 0:00:00,03:03:00 PM,CST,7.0,...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: Seasonably warm and dry con...
900809.0,27.0,10/5/2011 0:00:00,03:00:00 PM,CST,5.0,...,0.0,0.0,0.0,0.0,EPISODE NARRATIVE: A wildfire originated in Ju...

In [22]:
df.rename(columns = {'FATALITIES': 'Fatalities', 'INJURIES': 'Injuries'}, inplace = True)

In [23]:
np.sort(df.PROPDMGEXP.unique())

array([nan, '+', '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '?',
       'B', 'H', 'K', 'M', 'h', 'm'], dtype=object)

In [24]:
np.sort(df.CROPDMGEXP.unique())

array([nan, '0', '2', '?', 'B', 'K', 'M', 'k', 'm'], dtype=object)

In [25]:
exponent_to_multiplier = {
    '+': np.nan, '-': np.nan, '?': np.nan,
    '0': 10 ** 0,
    '1': 10 ** 1,
    '2': 10 ** 2, 'H': 10 ** 2, 'h': 10 ** 2,
    '3': 10 ** 3,'K': 10 ** 3,'k': 10 ** 3,
    '4': 10 ** 4,
    '5': 10 ** 5,
    '6': 10 ** 6, 'M': 10 ** 6, 'm': 10 ** 6,
    '7': 10 ** 7,
    '8': 10 ** 8,
    'B': 10 ** 9
}

In [26]:
df['PropertyDamages'] = df.PROPDMG * df.PROPDMGEXP.map(exponent_to_multiplier)

In [27]:
df['CropDamages'] = df.CROPDMG * df.CROPDMGEXP.map(exponent_to_multiplier)

In [28]:
df.PropertyDamages

REFNUM
1.0         25000.0
2.0          2500.0
3.0         25000.0
4.0          2500.0
5.0          2500.0
             ...
902293.0        0.0
902294.0        0.0
902295.0        0.0
902296.0        0.0
902297.0        0.0
Name: PropertyDamages, dtype: float64

In [29]:
df.drop(['PROPDMG', 'PROPDMGEXP', 'CROPDMG', 'CROPDMGEXP'], axis = 1, inplace = True)

In [30]:
df

,STATE__,BGN_DATE,BGN_TIME,TIME_ZONE,COUNTY,...,LATITUDE_E,LONGITUDE_,REMARKS,PropertyDamages,CropDamages
REFNUM,,,,,,,,,,,
1.0,1.0,4/18/1950 0:00:00,130,CST,97.0,...,3051.0,8806.0,NaN,25000.0,NaN
2.0,1.0,4/18/1950 0:00:00,145,CST,3.0,...,0.0,0.0,NaN,2500.0,NaN
3.0,1.0,2/20/1951 0:00:00,1600,CST,57.0,...,0.0,0.0,NaN,25000.0,NaN
4.0,1.0,6/8/1951 0:00:00,900,CST,89.0,...,0.0,0.0,NaN,2500.0,NaN
5.0,1.0,11/15/1951 0:00:00,1500,CST,43.0,...,0.0,0.0,NaN,2500.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
902293.0,56.0,11/30/2011 0:00:00,10:30:00 PM,MST,7.0,...,0.0,0.0,EPISODE NARRATIVE: A strong cold front moved s...,0.0,0.0
902294.0,30.0,11/10/2011 0:00:00,02:48:00 PM,MST,9.0,...,0.0,0.0,EPISODE NARRATIVE: A strong westerly flow alof...,0.0,0.0
902295.0,2.0,11/8/2011 0:00:00,02:58:00 PM,AKS,213.0,...,0.0,0.0,EPISODE NARRATIVE: A 960 mb low over the south...,0.0,0.0
902296.0,2.0,11/9/2011 0:00:00,10:21:00 AM,AKS,202.0,...,0.0,0.0,EPISODE NARRATIVE: A 960 mb low over the south...,0.0,0.0
902297.0,1.0,11/28/2011 0:00:00,08:00:00 PM,CST,6.0,...,0.0,0.0,EPISODE NARRATIVE: An intense upper level low ...,0.0,0.0

In [31]:
fatalities = df.Fatalities.sum()
injuries = df.Injuries.sum()
property_damages = df.PropertyDamages.sum()
crop_damages = df.CropDamages.sum()

In [32]:
print fatalities
print injuries

# Converting damamges from $ to $B
print property_damages / (10 ** 6)
print crop_damages / (10 ** 6)

15145.0
140528.0
428224.868108
49104.19217

In [33]:
df.shape[0]

902297

In [34]:
df[(df.Fatalities > 0) | (df.Injuries > 0) | (df.PropertyDamages > 0) | (df.CropDamages > 0)].shape[0]

254558

In [35]:
df = df[(df.Fatalities > 0) | (df.Injuries > 0) | (df.PropertyDamages > 0) | (df.CropDamages > 0)]

In [36]:
np.sort(df.EVTYPE.unique())

array(['   HIGH SURF ADVISORY', ' FLASH FLOOD', ' TSTM WIND',
       ' TSTM WIND (G45)', '?', 'AGRICULTURAL FREEZE', 'APACHE COUNTY',
       'ASTRONOMICAL HIGH TIDE', 'ASTRONOMICAL LOW TIDE', 'AVALANCE',
       'AVALANCHE', 'BLACK ICE', 'BLIZZARD', 'BLIZZARD/WINTER STORM',
       'BLOWING DUST', 'BLOWING SNOW', 'BRUSH FIRE', 'Beach Erosion',
       'COASTAL  FLOODING/EROSION', 'COASTAL EROSION', 'COASTAL FLOOD',
       'COASTAL FLOODING', 'COASTAL FLOODING/EROSION', 'COASTAL STORM',
       'COASTAL SURGE', 'COASTALSTORM', 'COLD', 'COLD AIR TORNADO',
       'COLD AND SNOW', 'COLD AND WET CONDITIONS', 'COLD WAVE',
       'COLD WEATHER', 'COLD/WIND CHILL', 'COLD/WINDS', 'COOL AND WET',
       'Coastal Flood', 'Coastal Flooding', 'Coastal Storm', 'Cold',
       'Cold Temperature', 'DAM BREAK', 'DAMAGING FREEZE', 'DENSE FOG',
       'DENSE SMOKE', 'DOWNBURST', 'DROUGHT', 'DROUGHT/EXCESSIVE HEAT',
       'DROWNING', 'DRY MICROBURST', 'DRY MIRCOBURST WINDS', 'DUST DEVIL',
       'DUST DEVIL WATERSPOUT', 'DUST STORM', 'DUST STORM/HIGH WINDS',
       'Damaging Freeze', 'Dust Devil', 'EXCESSIVE HEAT',
       'EXCESSIVE RAINFALL', 'EXCESSIVE SNOW', 'EXCESSIVE WETNESS',
       'EXTREME COLD', 'EXTREME COLD/WIND CHILL', 'EXTREME HEAT',
       'EXTREME WIND CHILL', 'EXTREME WINDCHILL', 'Early Frost',
       'Erosion/Cstl Flood', 'Extended Cold', 'Extreme Cold',
       'FALLING SNOW/ICE', 'FLASH FLOOD', 'FLASH FLOOD - HEAVY RAIN',
       'FLASH FLOOD FROM ICE JAMS', 'FLASH FLOOD LANDSLIDES',
       'FLASH FLOOD/', 'FLASH FLOOD/ STREET', 'FLASH FLOOD/FLOOD',
       'FLASH FLOOD/LANDSLIDE', 'FLASH FLOODING', 'FLASH FLOODING/FLOOD',
       'FLASH FLOODING/THUNDERSTORM WI', 'FLASH FLOODS', 'FLOOD',
       'FLOOD & HEAVY RAIN', 'FLOOD FLASH', 'FLOOD/FLASH',
       'FLOOD/FLASH FLOOD', 'FLOOD/FLASH/FLOOD', 'FLOOD/FLASHFLOOD',
       'FLOOD/RAIN/WINDS', 'FLOOD/RIVER FLOOD', 'FLOODING', 'FLOODS',
       'FOG', 'FOG AND COLD TEMPERATURES', 'FOREST FIRES', 'FREEZE',
       'FREEZING DRIZZLE', 'FREEZING FOG', 'FREEZING RAIN',
       'FREEZING RAIN/SLEET', 'FREEZING RAIN/SNOW', 'FROST',
       'FROST/FREEZE', 'FROST\\FREEZE', 'FUNNEL CLOUD', 'Freeze',
       'Freezing Drizzle', 'Freezing Rain', 'Freezing Spray',
       'Freezing drizzle', 'Frost/Freeze', 'GLAZE', 'GLAZE ICE',
       'GLAZE/ICE STORM', 'GRADIENT WIND', 'GRASS FIRES',
       'GROUND BLIZZARD', 'GUSTNADO', 'GUSTY WIND', 'GUSTY WIND/HAIL',
       'GUSTY WIND/HVY RAIN', 'GUSTY WINDS', 'Glaze', 'Gradient wind',
       'Gusty Winds', 'Gusty wind/rain', 'Gusty winds', 'HAIL',
       'HAIL 0.75', 'HAIL 075', 'HAIL 100', 'HAIL 125', 'HAIL 150',
       'HAIL 175', 'HAIL 200', 'HAIL 275', 'HAIL 450', 'HAIL 75',
       'HAIL DAMAGE', 'HAIL/WIND', 'HAIL/WINDS', 'HAILSTORM',
       'HARD FREEZE', 'HAZARDOUS SURF', 'HEAT', 'HEAT WAVE',
       'HEAT WAVE DROUGHT', 'HEAT WAVES', 'HEAVY LAKE SNOW', 'HEAVY MIX',
       'HEAVY PRECIPITATION', 'HEAVY RAIN', 'HEAVY RAIN AND FLOOD',
       'HEAVY RAIN/LIGHTNING', 'HEAVY RAIN/SEVERE WEATHER',
       'HEAVY RAIN/SMALL STREAM URBAN', 'HEAVY RAIN/SNOW', 'HEAVY RAINS',
       'HEAVY RAINS/FLOODING', 'HEAVY SEAS', 'HEAVY SHOWER', 'HEAVY SNOW',
       'HEAVY SNOW AND HIGH WINDS', 'HEAVY SNOW AND STRONG WINDS',
       'HEAVY SNOW SQUALLS', 'HEAVY SNOW-SQUALLS', 'HEAVY SNOW/BLIZZARD',
       'HEAVY SNOW/BLIZZARD/AVALANCHE', 'HEAVY SNOW/FREEZING RAIN',
       'HEAVY SNOW/HIGH WINDS & FLOOD', 'HEAVY SNOW/ICE',
       'HEAVY SNOW/SQUALLS', 'HEAVY SNOW/WIND', 'HEAVY SNOW/WINTER STORM',
       'HEAVY SNOWPACK', 'HEAVY SURF', 'HEAVY SURF COASTAL FLOODING',
       'HEAVY SURF/HIGH SURF', 'HEAVY SWELLS', 'HIGH', 'HIGH  WINDS',
       'HIGH SEAS', 'HIGH SURF', 'HIGH SWELLS', 'HIGH TIDES', 'HIGH WATER',
       'HIGH WAVES', 'HIGH WIND', 'HIGH WIND (G40)', 'HIGH WIND 48',
       'HIGH WIND AND SEAS', 'HIGH WIND DAMAGE', 'HIGH WIND/BLIZZARD',
       'HIGH WIND/HEAVY SNOW', 'HIGH WIND/SEAS', 'HIGH WINDS',
       'HIGH WINDS HEAVY RAINS', 'HIGH WINDS/', 'HIGH WINDS/COASTAL FLOOD',
       'HIGH WINDS/COLD', 'HIGH WINDS/HEAVY RAIN', 'HIGH WINDS/SNOW',
       'HURRICANE', 'HURRICANE EMILY', 'HURRICANE ERIN', 'HURRICANE FELIX',
       'HURRICANE GORDON', 'HURRICANE OPAL', 'HURRICANE OPAL/HIGH WINDS',
       'HURRICANE-GENERATED SWELLS', 'HURRICANE/TYPHOON', 'HVY RAIN',
       'HYPERTHERMIA/EXPOSURE', 'HYPOTHERMIA', 'HYPOTHERMIA/EXPOSURE',
       'Heat Wave', 'Heavy Rain/High Surf', 'Heavy Surf',
       'Heavy snow shower', 'Heavy surf and wind', 'High Surf',
       'Hurricane Edouard', 'Hypothermia/Exposure', 'ICE', 'ICE AND SNOW',
       'ICE FLOES', 'ICE JAM', 'ICE JAM FLOODING', 'ICE ON ROAD',
       'ICE ROADS', 'ICE STORM', 'ICE STORM/FLASH FLOOD',
       'ICE/STRONG WINDS', 'ICY ROADS', 'Ice jam flood (minor',
       'LAKE EFFECT SNOW', 'LAKE FLOOD', 'LAKE-EFFECT SNOW',
       'LAKESHORE FLOOD', 'LANDSLIDE', 'LANDSLIDES', 'LANDSPOUT',
       'LATE SEASON SNOW', 'LIGHT FREEZING RAIN', 'LIGHT SNOW', 'LIGHTING',
       'LIGHTNING', 'LIGHTNING  WAUSEON', 'LIGHTNING AND HEAVY RAIN',
       'LIGHTNING AND THUNDERSTORM WIN', 'LIGHTNING FIRE',
       'LIGHTNING INJURY', 'LIGHTNING THUNDERSTORM WINDS', 'LIGHTNING.',
       'LIGHTNING/HEAVY RAIN', 'LIGNTNING', 'LOW TEMPERATURE',
       'Lake Effect Snow', 'Landslump', 'Light Snow', 'Light Snowfall',
       'Light snow', 'MAJOR FLOOD', 'MARINE HAIL', 'MARINE HIGH WIND',
       'MARINE MISHAP', 'MARINE STRONG WIND', 'MARINE THUNDERSTORM WIND',
       'MARINE TSTM WIND', 'MICROBURST', 'MICROBURST WINDS',
       'MINOR FLOODING', 'MIXED PRECIP', 'MIXED PRECIPITATION',
       'MUD SLIDE', 'MUD SLIDES', 'MUD SLIDES URBAN FLOODING', 'MUDSLIDE',
       'MUDSLIDES', 'Marine Accident', 'Microburst', 'Mixed Precipitation',
       'Mudslide', 'Mudslides', 'NON TSTM WIND', 'NON-SEVERE WIND DAMAGE',
       'NON-TSTM WIND', 'OTHER', 'Other', 'RAIN', 'RAIN/SNOW', 'RAIN/WIND',
       'RAINSTORM', 'RAPIDLY RISING WATER', 'RECORD COLD', 'RECORD HEAT',
       'RECORD RAINFALL', 'RECORD SNOW', 'RECORD/EXCESSIVE HEAT',
       'RIP CURRENT', 'RIP CURRENTS', 'RIP CURRENTS/HEAVY SURF',
       'RIVER AND STREAM FLOOD', 'RIVER FLOOD', 'RIVER FLOODING',
       'ROCK SLIDE', 'ROGUE WAVE', 'ROUGH SEAS', 'ROUGH SURF',
       'RURAL FLOOD', 'River Flooding', 'SEICHE', 'SEVERE THUNDERSTORM',
       'SEVERE THUNDERSTORM WINDS', 'SEVERE THUNDERSTORMS',
       'SEVERE TURBULENCE', 'SLEET', 'SLEET/ICE STORM', 'SMALL HAIL',
       'SMALL STREAM FLOOD', 'SNOW', 'SNOW ACCUMULATION',
       'SNOW AND HEAVY SNOW', 'SNOW AND ICE', 'SNOW AND ICE STORM',
       'SNOW FREEZING RAIN', 'SNOW SQUALL', 'SNOW SQUALLS',
       'SNOW/ BITTER COLD', 'SNOW/ ICE', 'SNOW/BLOWING SNOW', 'SNOW/COLD',
       'SNOW/FREEZING RAIN', 'SNOW/HEAVY SNOW', 'SNOW/HIGH WINDS',
       'SNOW/ICE', 'SNOW/ICE STORM', 'SNOW/SLEET',
       'SNOW/SLEET/FREEZING RAIN', 'SNOWMELT FLOODING',
       'STORM FORCE WINDS', 'STORM SURGE', 'STORM SURGE/TIDE',
       'STRONG WIND', 'STRONG WINDS', 'Snow', 'Snow Squalls',
       'Strong Wind', 'Strong Winds', 'THUDERSTORM WINDS',
       'THUNDEERSTORM WINDS', 'THUNDERESTORM WINDS', 'THUNDERSNOW',
       'THUNDERSTORM', 'THUNDERSTORM  WINDS', 'THUNDERSTORM DAMAGE TO',
       'THUNDERSTORM HAIL', 'THUNDERSTORM WIND', 'THUNDERSTORM WIND (G40)',
       'THUNDERSTORM WIND 60 MPH', 'THUNDERSTORM WIND 65 MPH',
       'THUNDERSTORM WIND 65MPH', 'THUNDERSTORM WIND 98 MPH',
       'THUNDERSTORM WIND G50', 'THUNDERSTORM WIND G52',
       'THUNDERSTORM WIND G55', 'THUNDERSTORM WIND G60',
       'THUNDERSTORM WIND TREES', 'THUNDERSTORM WIND.',
       'THUNDERSTORM WIND/ TREE', 'THUNDERSTORM WIND/ TREES',
       'THUNDERSTORM WIND/AWNING', 'THUNDERSTORM WIND/HAIL',
       'THUNDERSTORM WIND/LIGHTNING', 'THUNDERSTORM WINDS',
       'THUNDERSTORM WINDS 13', 'THUNDERSTORM WINDS 63 MPH',
       'THUNDERSTORM WINDS AND', 'THUNDERSTORM WINDS G60',
       'THUNDERSTORM WINDS HAIL', 'THUNDERSTORM WINDS LIGHTNING',
       'THUNDERSTORM WINDS.', 'THUNDERSTORM WINDS/ FLOOD',
       'THUNDERSTORM WINDS/FLOODING', 'THUNDERSTORM WINDS/FUNNEL CLOU',
       'THUNDERSTORM WINDS/HAIL', 'THUNDERSTORM WINDS53',
       'THUNDERSTORM WINDSHAIL', 'THUNDERSTORM WINDSS',
       'THUNDERSTORM WINS', 'THUNDERSTORMS', 'THUNDERSTORMS WIND',
       'THUNDERSTORMS WINDS', 'THUNDERSTORMW', 'THUNDERSTORMWINDS',
       'THUNDERSTROM WIND', 'THUNDERTORM WINDS', 'THUNERSTORM WINDS',
       'TIDAL FLOODING', 'TORNADO', 'TORNADO F0', 'TORNADO F1',
       'TORNADO F2', 'TORNADO F3', 'TORNADOES',
       'TORNADOES, TSTM WIND, HAIL', 'TORNDAO', 'TROPICAL DEPRESSION',
       'TROPICAL STORM', 'TROPICAL STORM ALBERTO', 'TROPICAL STORM DEAN',
       'TROPICAL STORM GORDON', 'TROPICAL STORM JERRY', 'TSTM WIND',
       'TSTM WIND  (G45)', 'TSTM WIND (41)', 'TSTM WIND (G35)',
       'TSTM WIND (G40)', 'TSTM WIND (G45)', 'TSTM WIND 40',
       'TSTM WIND 45', 'TSTM WIND 55', 'TSTM WIND 65)',
       'TSTM WIND AND LIGHTNING', 'TSTM WIND DAMAGE', 'TSTM WIND G45',
       'TSTM WIND G58', 'TSTM WIND/HAIL', 'TSTM WINDS', 'TSTMW', 'TSUNAMI',
       'TUNDERSTORM WIND', 'TYPHOON', 'Tidal Flooding',
       'Torrential Rainfall', 'Tstm Wind', 'UNSEASONABLY COLD',
       'UNSEASONABLY WARM', 'UNSEASONABLY WARM AND DRY', 'UNSEASONAL RAIN',
       'URBAN AND SMALL', 'URBAN AND SMALL STREAM FLOODIN', 'URBAN FLOOD',
       'URBAN FLOODING', 'URBAN FLOODS', 'URBAN SMALL',
       'URBAN/SMALL STREAM', 'URBAN/SMALL STREAM FLOOD',
       'URBAN/SML STREAM FLD', 'Unseasonable Cold', 'VOLCANIC ASH',
       'WARM WEATHER', 'WATERSPOUT', 'WATERSPOUT TORNADO', 'WATERSPOUT-',
       'WATERSPOUT-TORNADO', 'WATERSPOUT/ TORNADO', 'WATERSPOUT/TORNADO',
       'WET MICROBURST', 'WHIRLWIND', 'WILD FIRES', 'WILD/FOREST FIRE',
       'WILD/FOREST FIRES', 'WILDFIRE', 'WILDFIRES', 'WIND',
       'WIND AND WAVE', 'WIND DAMAGE', 'WIND STORM', 'WIND/HAIL', 'WINDS',
       'WINTER STORM', 'WINTER STORM HIGH WINDS', 'WINTER STORMS',
       'WINTER WEATHER', 'WINTER WEATHER MIX', 'WINTER WEATHER/MIX',
       'WINTRY MIX', 'Whirlwind', 'Wind', 'Wind Damage', 'Wintry Mix',
       'blowing snow', 'gradient wind'], dtype=object)

In [37]:
len(df.EVTYPE.unique())

485

In [38]:
df['EVTYPE'] = df.EVTYPE.apply(lambda event_type: event_type.strip().upper())

/Users/samuelleichman/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':