In [54]:
import os

import math

import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 20)
pd.set_option('display.notebook_repr_html', True)
pd.set_option('display.max_columns', 10)

import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

In [55]:
df = pd.read_csv('/Users/samuelleichman/DS-SF-30/unit-project/dataset/Q107II.csv')

In [56]:
var = df.iloc[4,8]

In [57]:
df.index

RangeIndex(start=0, stop=6208, step=1)

In [58]:
df.isnull().sum().sum()

86

In [59]:
df.dtypes

ShipDate                   object
OrderNumber                object
ItemCode                   object
ItemDescription            object
OrderLocation              object
SKUCode                     int64
Department                 object
UnitsSold                 float64
TotalNetRevenue            object
TotalCOGS                  object
GrossMarginDollars         object
GrossMarginPercent         object
CurrentAverageCost         object
CurrentRetailPriceEach     object
Current_GM_Each           float64
Class                      object
Category                   object
Sub_Class                  object
Quarter                    object
dtype: object

In [60]:
df.isnull()

,ShipDate,OrderNumber,ItemCode,ItemDescription,OrderLocation,...,Current_GM_Each,Class,Category,Sub_Class,Quarter
0,False,False,False,False,False,...,False,False,False,False,False
1,False,False,False,False,False,...,False,False,False,False,False
2,False,False,False,False,False,...,False,False,False,False,False
3,False,False,False,False,False,...,False,False,False,False,False
4,False,False,False,False,False,...,False,False,False,False,False
5,False,False,False,False,False,...,False,False,False,False,False
6,False,False,False,False,False,...,False,False,False,False,False
7,False,False,False,False,False,...,False,False,False,False,False
8,False,False,False,False,False,...,False,False,False,False,False
9,False,False,False,False,False,...,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
6198,False,False,False,False,False,...,False,False,False,False,False
6199,False,False,False,False,False,...,False,False,False,False,False
6200,False,False,False,False,False,...,False,False,False,False,False
6201,False,False,False,False,False,...,False,False,False,False,False
6202,False,False,False,False,False,...,False,False,False,False,False
6203,False,False,False,False,False,...,False,False,False,False,False
6204,False,False,False,False,False,...,False,False,False,False,False
6205,False,False,False,False,False,...,False,False,False,False,False
6206,False,False,False,False,False,...,False,False,False,False,False
6207,False,False,False,False,False,...,False,False,False,False,False

In [61]:
df.index

RangeIndex(start=0, stop=6208, step=1)

In [62]:
type(df.index)

pandas.indexes.range.RangeIndex

In [63]:
df.columns

Index([u'ShipDate', u'OrderNumber', u'ItemCode', u'ItemDescription',
       u'OrderLocation', u'SKUCode', u'Department', u'UnitsSold',
       u'TotalNetRevenue', u'TotalCOGS', u'GrossMarginDollars',
       u'GrossMarginPercent', u'CurrentAverageCost', u'CurrentRetailPriceEach',
       u'Current_GM_Each', u'Class', u'Category', u'Sub_Class', u'Quarter'],
      dtype='object')

In [64]:
df[['Department','Class']]

     Department     Class
0      LIGHTING  PENDANTS
1      LIGHTING  PENDANTS
2      LIGHTING  PENDANTS
3      LIGHTING  PENDANTS
4      LIGHTING  PENDANTS
5      LIGHTING  PENDANTS
6      LIGHTING  PENDANTS
7      LIGHTING  PENDANTS
8      LIGHTING  PENDANTS
9      LIGHTING  PENDANTS
...         ...       ...
6198   LIGHTING     FLOOR
6199   LIGHTING      TASK
6200   LIGHTING     TABLE
6201   LIGHTING     TABLE
6202   LIGHTING     FLOOR
6203   LIGHTING     FLOOR
6204   LIGHTING     TABLE
6205   LIGHTING  PENDANTS
6206   LIGHTING  PENDANTS
6207   LIGHTING  PENDANTS

[6208 rows x 2 columns]

In [65]:
df.columns

Index([u'ShipDate', u'OrderNumber', u'ItemCode', u'ItemDescription',
       u'OrderLocation', u'SKUCode', u'Department', u'UnitsSold',
       u'TotalNetRevenue', u'TotalCOGS', u'GrossMarginDollars',
       u'GrossMarginPercent', u'CurrentAverageCost', u'CurrentRetailPriceEach',
       u'Current_GM_Each', u'Class', u'Category', u'Sub_Class', u'Quarter'],
      dtype='object')

In [66]:
df.OrderNumber

0         G0784135
1         G0792852
2       WEB0784998
3       WEB0786966
4       WEB0790371
5       WEB0791955
6       WEB0792086
7         G0790461
8         G0791465
9         G0784248
           ...
6198      G0811143
6199      G0837069
6200      G0794773
6201      G0794773
6202      G0821027
6203      G0825669
6204      G0790232
6205      G0796690
6206      G0817437
6207      G0818455
Name: OrderNumber, dtype: object

In [67]:
df[[df.columns.get_loc('OrderNumber')]]

     OrderNumber
0       G0784135
1       G0792852
2     WEB0784998
3     WEB0786966
4     WEB0790371
5     WEB0791955
6     WEB0792086
7       G0790461
8       G0791465
9       G0784248
...          ...
6198    G0811143
6199    G0837069
6200    G0794773
6201    G0794773
6202    G0821027
6203    G0825669
6204    G0790232
6205    G0796690
6206    G0817437
6207    G0818455

[6208 rows x 1 columns]

In [68]:
df[['OrderNumber']]

     OrderNumber
0       G0784135
1       G0792852
2     WEB0784998
3     WEB0786966
4     WEB0790371
5     WEB0791955
6     WEB0792086
7       G0790461
8       G0791465
9       G0784248
...          ...
6198    G0811143
6199    G0837069
6200    G0794773
6201    G0794773
6202    G0821027
6203    G0825669
6204    G0790232
6205    G0796690
6206    G0817437
6207    G0818455

[6208 rows x 1 columns]

In [69]:
df[:5]

,ShipDate,OrderNumber,ItemCode,ItemDescription,OrderLocation,...,Current_GM_Each,Class,Category,Sub_Class,Quarter
0,1/3/2007 12:00:00 AM,G0784135,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",200 - DWR Call Center,...,52.31,PENDANTS,MISC,MISC,Q1 07
1,1/3/2007 12:00:00 AM,G0792852,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",200 - DWR Call Center,...,52.31,PENDANTS,MISC,MISC,Q1 07
2,1/3/2007 12:00:00 AM,WEB0784998,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",205 - zz_Website - dwr.com,...,52.31,PENDANTS,MISC,MISC,Q1 07
3,1/3/2007 12:00:00 AM,WEB0786966,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",205 - zz_Website - dwr.com,...,52.31,PENDANTS,MISC,MISC,Q1 07
4,1/3/2007 12:00:00 AM,WEB0790371,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",205 - zz_Website - dwr.com,...,52.31,PENDANTS,MISC,MISC,Q1 07

In [70]:
df.index

RangeIndex(start=0, stop=6208, step=1)

In [71]:
df.columns

Index([u'ShipDate', u'OrderNumber', u'ItemCode', u'ItemDescription',
       u'OrderLocation', u'SKUCode', u'Department', u'UnitsSold',
       u'TotalNetRevenue', u'TotalCOGS', u'GrossMarginDollars',
       u'GrossMarginPercent', u'CurrentAverageCost', u'CurrentRetailPriceEach',
       u'Current_GM_Each', u'Class', u'Category', u'Sub_Class', u'Quarter'],
      dtype='object')

In [72]:
df.drop(['Current_GM_Each'], axis = 1, inplace =True)

In [73]:
df.columns

Index([u'ShipDate', u'OrderNumber', u'ItemCode', u'ItemDescription',
       u'OrderLocation', u'SKUCode', u'Department', u'UnitsSold',
       u'TotalNetRevenue', u'TotalCOGS', u'GrossMarginDollars',
       u'GrossMarginPercent', u'CurrentAverageCost', u'CurrentRetailPriceEach',
       u'Class', u'Category', u'Sub_Class', u'Quarter'],
      dtype='object')

In [74]:
df

,ShipDate,OrderNumber,ItemCode,ItemDescription,OrderLocation,...,CurrentRetailPriceEach,Class,Category,Sub_Class,Quarter
0,1/3/2007 12:00:00 AM,G0784135,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",200 - DWR Call Center,...,300.00,PENDANTS,MISC,MISC,Q1 07
1,1/3/2007 12:00:00 AM,G0792852,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",200 - DWR Call Center,...,300.00,PENDANTS,MISC,MISC,Q1 07
2,1/3/2007 12:00:00 AM,WEB0784998,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",205 - zz_Website - dwr.com,...,300.00,PENDANTS,MISC,MISC,Q1 07
3,1/3/2007 12:00:00 AM,WEB0786966,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",205 - zz_Website - dwr.com,...,300.00,PENDANTS,MISC,MISC,Q1 07
4,1/3/2007 12:00:00 AM,WEB0790371,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",205 - zz_Website - dwr.com,...,300.00,PENDANTS,MISC,MISC,Q1 07
5,1/3/2007 12:00:00 AM,WEB0791955,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",205 - zz_Website - dwr.com,...,300.00,PENDANTS,MISC,MISC,Q1 07
6,1/3/2007 12:00:00 AM,WEB0792086,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",205 - zz_Website - dwr.com,...,300.00,PENDANTS,MISC,MISC,Q1 07
7,1/3/2007 12:00:00 AM,G0790461,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",213 - Santa Monica Studio,...,300.00,PENDANTS,MISC,MISC,Q1 07
8,1/3/2007 12:00:00 AM,G0791465,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",216 - Portland Studio,...,300.00,PENDANTS,MISC,MISC,Q1 07
9,1/3/2007 12:00:00 AM,G0784248,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",227 - Brooklyn Heights Studio,...,300.00,PENDANTS,MISC,MISC,Q1 07
...,...,...,...,...,...,...,...,...,...,...,...
6198,2/1/2007 12:00:00 AM,G0811143,C4318 STEEL.GREY,"Arco Floor Lamp - Shade, Steel Grey",200 - DWR Call Center,...,460.00,FLOOR,MISC,MISC,Q1 07
6199,3/16/2007 12:00:00 AM,G0837069,C6987 ALUMINUM,Kelvin Task Lamp - Base,245 - Minneapolis Studio,...,81.00,TASK,MISC,MISC,Q1 07
6200,1/6/2007 12:00:00 AM,G0794773,C7080 CHROME,"Pantop Table Lamp Small - Base, Chrome",249 - Birmingham Studio,...,175.00,TABLE,MISC,MISC,Q1 07
6201,1/6/2007 12:00:00 AM,G0794773,C7081 CHROME,"Pantop Table Lamp Small - Shade, Chrome",249 - Birmingham Studio,...,174.95,TABLE,MISC,MISC,Q1 07
6202,2/23/2007 12:00:00 AM,G0821027,C8224 NATURAL,"Gilda Floor Lamp Shade , Natural",223 - Chelsea Studio,...,445.62,FLOOR,MISC,MISC,Q1 07
6203,3/12/2007 12:00:00 AM,G0825669,C8224 NATURAL,"Gilda Floor Lamp Shade , Natural",221 - Soho Studio,...,445.62,FLOOR,MISC,MISC,Q1 07
6204,1/3/2007 12:00:00 AM,G0790232,C9518 OPALINE,"Mirandolina - Opal Dome, Opaline",271 - Potrero Studio,...,210.00,TABLE,MISC,MISC,Q1 07
6205,1/10/2007 12:00:00 AM,G0796690,C9803 ALUMINUM,"Cellula Chandelier - 32 in. Rod, Aluminum",234 - North Avenue Studio,...,"1,000.00",PENDANTS,MISC,MISC,Q1 07
6206,2/14/2007 12:00:00 AM,G0817437,P8764 NONE,"Nelson Lamp Ceiling Plate and Hardware, None",230 - Berkeley Studio,...,20.00,PENDANTS,MISC,MISC,Q1 07
6207,2/20/2007 12:00:00 AM,G0818455,P8764 NONE,"Nelson Lamp Ceiling Plate and Hardware, None",271 - Potrero Studio,...,20.00,PENDANTS,MISC,MISC,Q1 07

In [75]:
df.CurrentRetailPriceEach.unique()

array(['300.00', '368.00', '533.00', '370.00', '350.00', '1,212.00',
       '108.00', '944.00', '2,548.00', '2,696.00', '390.00', '348.00',
       '2,112.00', '510.00', '239.00', '299.00', '365.00', '5,000.00',
       '900.00', '750.00', '278.00', '248.00', '200.00', '136.00',
       '285.00', '500.00', '100.00', '1.00', '144.00', '748.00', '332.00',
       '596.00', '3,516.00', '548.00', '380.00', '848.00', '399.00',
       '12.00', '775.00', '6.00', '5.00', '491.00', '325.00', '298.00',
       '475.00', '724.00', '948.00', '1,028.00', '1,396.00', '1,520.00',
       '276.00', '4,984.00', '267.00', '275.00', '159.95', '330.00',
       '435.00', '395.00', '648.00', '7,312.00', '698.00', '1,460.00',
       '250.00', '98.00', '2.75', '2.50', '3.00', '20.00', '10.00',
       '19.00', '0.81', '3.25', '2.00', '170.00', '1,165.00', '3,200.00',
       '3.50', '11.00', '1.50', '0.85', '329.00', '289.95', '293.00',
       '310.00', '398.00', '448.00', '280.00', '198.00', '2,998.00',
       '1,032.00', '1,740.00', '106.25', '125.00', '604.00', '988.00',
       '1,350.00', '660.00', '299.95', '448.50', '778.00', '860.00',
       '1,700.00', '264.00', '362.00', '840.00', '139.95', '700.00',
       '449.95', '128.00', '288.00', '89.95', '599.95', '1,100.00',
       '399.95', '2,600.00', '530.00', '590.00', '199.95', '2,100.00',
       '220.00', '1,598.00', '110.00', '400.00', '1,498.50', '1,898.00',
       '269.00', '227.00', '555.00', '650.00', '2,000.00', '9.98',
       '360.00', '352.00', '3,505.58', '134.53', '89.07', '244.00',
       '129.07', '1,302.22', '131.68', '263.32', '460.00', '81.00',
       '175.00', '174.95', '445.62', '210.00', '1,000.00'], dtype=object)

In [76]:
df_1 = df[df.CurrentRetailPriceEach == '$']
df_1 = df_1.drop('CurrentRetailPriceEach', axis = 1)

df_1.TotalNetRevenue /10 ** 6

Series([], Name: TotalNetRevenue, dtype: object)

In [77]:
df_1

Empty DataFrame
Columns: [ShipDate, OrderNumber, ItemCode, ItemDescription, OrderLocation, SKUCode, Department, UnitsSold, TotalNetRevenue, TotalCOGS, GrossMarginDollars, GrossMarginPercent, CurrentAverageCost, Class, Category, Sub_Class, Quarter]
Index: []

[0 rows x 17 columns]

In [78]:
df.ShipDate

0        1/3/2007  12:00:00 AM
1        1/3/2007  12:00:00 AM
2        1/3/2007  12:00:00 AM
3        1/3/2007  12:00:00 AM
4        1/3/2007  12:00:00 AM
5        1/3/2007  12:00:00 AM
6        1/3/2007  12:00:00 AM
7        1/3/2007  12:00:00 AM
8        1/3/2007  12:00:00 AM
9        1/3/2007  12:00:00 AM
                 ...
6198     2/1/2007  12:00:00 AM
6199    3/16/2007  12:00:00 AM
6200     1/6/2007  12:00:00 AM
6201     1/6/2007  12:00:00 AM
6202    2/23/2007  12:00:00 AM
6203    3/12/2007  12:00:00 AM
6204     1/3/2007  12:00:00 AM
6205    1/10/2007  12:00:00 AM
6206    2/14/2007  12:00:00 AM
6207    2/20/2007  12:00:00 AM
Name: ShipDate, dtype: object

In [79]:
pd.to_datetime(df.ShipDate)

0      2007-01-03
1      2007-01-03
2      2007-01-03
3      2007-01-03
4      2007-01-03
5      2007-01-03
6      2007-01-03
7      2007-01-03
8      2007-01-03
9      2007-01-03
          ...
6198   2007-02-01
6199   2007-03-16
6200   2007-01-06
6201   2007-01-06
6202   2007-02-23
6203   2007-03-12
6204   2007-01-03
6205   2007-01-10
6206   2007-02-14
6207   2007-02-20
Name: ShipDate, dtype: datetime64[ns]

In [80]:
df.ShipDate = pd.to_datetime(df.ShipDate)

In [81]:
df.ShipDate

0      2007-01-03
1      2007-01-03
2      2007-01-03
3      2007-01-03
4      2007-01-03
5      2007-01-03
6      2007-01-03
7      2007-01-03
8      2007-01-03
9      2007-01-03
          ...
6198   2007-02-01
6199   2007-03-16
6200   2007-01-06
6201   2007-01-06
6202   2007-02-23
6203   2007-03-12
6204   2007-01-03
6205   2007-01-10
6206   2007-02-14
6207   2007-02-20
Name: ShipDate, dtype: datetime64[ns]

In [91]:
df.ShipDate

AttributeError: 'DataFrame' object has no attribute 'ShipDate'

In [89]:
df

,OrderNumber,ItemCode,ItemDescription,OrderLocation,SKUCode,...,Quarter,YearOfSale,MonthOfSale,DayOfSale,WeekDayOfSale
0,G0784135,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",200 - DWR Call Center,101738,...,Q1 07,2007,1,3,Wednesday
1,G0792852,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",200 - DWR Call Center,101738,...,Q1 07,2007,1,3,Wednesday
2,WEB0784998,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",205 - zz_Website - dwr.com,101738,...,Q1 07,2007,1,3,Wednesday
3,WEB0786966,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",205 - zz_Website - dwr.com,101738,...,Q1 07,2007,1,3,Wednesday
4,WEB0790371,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",205 - zz_Website - dwr.com,101738,...,Q1 07,2007,1,3,Wednesday
5,WEB0791955,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",205 - zz_Website - dwr.com,101738,...,Q1 07,2007,1,3,Wednesday
6,WEB0792086,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",205 - zz_Website - dwr.com,101738,...,Q1 07,2007,1,3,Wednesday
7,G0790461,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",213 - Santa Monica Studio,101738,...,Q1 07,2007,1,3,Wednesday
8,G0791465,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",216 - Portland Studio,101738,...,Q1 07,2007,1,3,Wednesday
9,G0784248,0096 WHITE,"Nelson Saucer Pendant Lamp - Med, White",227 - Brooklyn Heights Studio,101738,...,Q1 07,2007,1,3,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...
6198,G0811143,C4318 STEEL.GREY,"Arco Floor Lamp - Shade, Steel Grey",200 - DWR Call Center,158268,...,Q1 07,2007,2,1,Thursday
6199,G0837069,C6987 ALUMINUM,Kelvin Task Lamp - Base,245 - Minneapolis Studio,199872,...,Q1 07,2007,3,16,Friday
6200,G0794773,C7080 CHROME,"Pantop Table Lamp Small - Base, Chrome",249 - Birmingham Studio,201285,...,Q1 07,2007,1,6,Saturday
6201,G0794773,C7081 CHROME,"Pantop Table Lamp Small - Shade, Chrome",249 - Birmingham Studio,201377,...,Q1 07,2007,1,6,Saturday
6202,G0821027,C8224 NATURAL,"Gilda Floor Lamp Shade , Natural",223 - Chelsea Studio,222075,...,Q1 07,2007,2,23,Friday
6203,G0825669,C8224 NATURAL,"Gilda Floor Lamp Shade , Natural",221 - Soho Studio,222075,...,Q1 07,2007,3,12,Monday
6204,G0790232,C9518 OPALINE,"Mirandolina - Opal Dome, Opaline",271 - Potrero Studio,247344,...,Q1 07,2007,1,3,Wednesday
6205,G0796690,C9803 ALUMINUM,"Cellula Chandelier - 32 in. Rod, Aluminum",234 - North Avenue Studio,253192,...,Q1 07,2007,1,10,Wednesday
6206,G0817437,P8764 NONE,"Nelson Lamp Ceiling Plate and Hardware, None",230 - Berkeley Studio,231312,...,Q1 07,2007,2,14,Wednesday
6207,G0818455,P8764 NONE,"Nelson Lamp Ceiling Plate and Hardware, None",271 - Potrero Studio,231312,...,Q1 07,2007,2,20,Tuesday